external:
  clients:
    base-url: https://clients.cluster.domain.cz
  accounts:
    base-url: https://accounts.cluster.domain.cz
  api-key: e02ff909-c6e6-4f7d-8937-bab69351e2d4 # fake/test value

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/case_study
    username: orders
    password: Passw0rd#1
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: INFO
    com.example.usereligibilityapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
